### ISSUE TITLE
[Send Money] User can attempt Transaction without selecting Receiver.

### ISSUE THREAD

**Issue by Harshitha20-MCA** [pioneer-pay/pioneer-pay-web-app#22]
**Steps To Reproduce**

> 1. Select a Source and Destination country from respective Dropdown
> 2. Enter Amount to send 
> 3. Click On Convert Button
> 4. Choose "Bank Account" payment method for Delivery and "Credit Card" method to Pay amount
> 5. Click on Continue Button
> 6. W/o Selecting Receiver, Click On 'Review and Confirm Transfer' Button

 **Expected Result**

- Error Message 'Please Select Receiver before Proceeding with Transaction' should be Displayed and restrict user to proceed with next step

**Actual Result**     

- Post click on 'Review and confirm Transfer' button user redirected to Confirm Transfer Page.

![Image](https://github.com/pioneer-pay/pioneer-pay-web-app/assets/68989269/7137af01-4ebe-4763-90ea-d331c1175ede)

![Image](https://github.com/pioneer-pay/pioneer-pay-web-app/assets/68989269/278a34b5-24dd-4629-8b7b-5c9d2793ce78)

**Comment by Mangesh-Shirodkar** [comment]
**Defect : DF_SM_04** has been successfully fixed and user cannot proceed with transaction without selecting receiver.



![Image](https://github.com/pioneer-pay/pioneer-pay-web-app/assets/68989269/ea7bc91e-6bf8-4499-bfde-953817e7750e)
