### ISSUE TITLE
As a user, I want to get a notification within the app whenever an action has been executed from the backend

### ISSUE THREAD

**Issue by naundhe** [pioneer-pay/pioneer-pay-web-app#35]
**Definition of Done** 

- Add Notification icon on navigation bar to display all notifications.
- Create table to store notifications.
- Create notification service.
- Add a limit to save notifications - older notification should delete automatically after some limit and show newer notifications.

**Technical Details**

- Add notification icon in navigation bar.
- Create notification controller to fetch notification from backend and show on webpage.
- Create notification.html file to show notifications also add some styling.

![Image](https://github.com/pioneer-pay/pioneer-pay-web-app/assets/92147674/bbc4ae0a-25b1-4602-8c51-2c767fa3ab30)

**Comment by Mangesh-Shirodkar** [comment]
- Feature: InApp Notification working fine with existing system.
- Automation Tests are successfully executed and passed.
- All identified bugs have been addressed and resolved.

![Image](https://github.com/pioneer-pay/pioneer-pay-web-app/assets/68989269/c9d3361d-b0d6-4f91-b528-ba7ff66b1acc)
