### ISSUE TITLE
As a user, I should be able to read notifications.

### ISSUE THREAD

**Issue by naundhe** [pioneer-pay/pioneer-pay-web-app#36]
**Definition of Done**

- When new notification come notify in app only how many unread notifications are there.
- User should be able to mark unread notification as read.

**Technical Details**

- Create notification service to return count of unread notifications.
- Create one controller which makes unread notifications as read.
- Use unread notification controller in html page.
- Use notification service in directives to show count of unread notification on notification icon.

![Image](https://github.com/pioneer-pay/pioneer-pay-web-app/assets/92147674/c0cb91f9-f66f-432b-9b32-559f44ef1bf9)

**Comment by naundhe** [comment]
- Need to make some change in design part of read notification.
- Which notification are read=true -> need to add tick mark after those notifications.

**Comment by Mangesh-Shirodkar** [comment]
- Feature: InApp Notification working fine with existing system.
- Automation Tests are successfully executed and passed.
- All identified bugs have been addressed and resolved.
