### ISSUE TITLE
[Print Receipt] After clicking on the print receipt, I was not able to click on any other buttons.

### ISSUE THREAD

**Issue by Krushnamasal** [pioneer-pay/pioneer-pay-web-app#82]
**Steps to Reproduce:**

Log in to the application.
Click on history button then click on print receipt button.
It will open new tab, go to the previous tab click on any button 

**Expected Behavior:**

Should be able to click on another button after opening a new tab or do open the print receipt page in the same window.

**Actual Behavior:**

Not able to click on the other button after clicking on print receipt

**Comment by SupriyaRevanwar** [comment]
![Image](https://github.com/pioneer-pay/pioneer-pay-web-app/assets/86201753/3dbc750e-7169-4978-816f-97b12561508d)

resolved error: now print window will open in same webpage.

**Comment by Krushnamasal** [comment]
The defect is resolved and working fine.
